



























}  }    // ...existing code...    configData.addAll(newConfig);  static void updateConfig(Map<String, dynamic> newConfig) {  }    }      // Optionally write the default config to file      };        // ...your default config...      configData = {    } else {      // ...existing code...      configData = {}; // Parse JSON into configData      // ...existing code...      final content = await file.readAsString();    if (await file.exists()) {    final file = File(filePath);    final filePath = '$home/.notpixelshot.json';    final home = Platform.environment['HOME'] ?? '';    // Pseudo-code for reading .notpixelshot.json in user home directory:  static Future<void> initialize() async {  static late Map<String, dynamic> configData;class ConfigService {import 'dart:io';